import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, {useState} from "react"
import Axios from 'axios'
export default function Home() {

//  async function handler(e){
//     e.preventDefault();
//     const response = await fetch ("http//localhost:5000/Register",{
//       method:"POST",
//       head:{"Content-Type":"application/json"},
//       body: JSON.stringify({
//         name:name,
//         age:age,
//         username:username
//       })
      
//     })
//     const data = await response.json();
//     if(error){
//       console.log(error)
//     }console.log(data)
//   }
   const handler = () => {
      Axios.post("http://localhost:5000/Register", {
        name,
        age,
        username,
      }).then((response) =>{
        alert("user created")
      });
   }
  const [name, setName] = useState()
  const [age, setAge] = useState()
  const [username, setUsername] = useState()
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <form onSubmit={handler}>  
          <div className={styles.main}>
             <input type='text' placeholder='NAME' onChange={(e)=> setName(e.target.value)}></input>
             <input type='number' placeholder='AGE' onChange={(e)=> setAge(e.target.value)}></input>
             <input type='text' placeholder='USERNAME' onChange={(e)=> setUsername(e.target.value)}></input>
             <button type='submit'>SUBMIT</button>
             </div>
        </form>

    </div>
  )
}
